### ISSUE TITLE
How to install validation in Eclipse?

### ISSUE THREAD

**Issue by fbastian** [angelozerr/tern-react#2]
I would like to install your plugin for syntax validation in Eclipse. I don't care about completion, I'm simply interested in writing JSX code in Eclipse. 

I manually created a `tern-react` folder in the plugin directory, and added the `package.json` and `react.js` files. The `react` module correctly shows up in the list of modules, in the Tern properties. However, it doesn't show up as a potential validation tool. 

Is there a way to have syntax validation for react/JSX in Eclipse using this plugin?

**Comment by angelozerr** [comment]
>  it doesn't show up as a potential validation tool.

Yes it's normal, tern-react is not a linter but should provide completion for JSX. But as acorn-jsx doesn't support loose parser (when JSX is not valid, it cannot work).

To support validation for JSX inside Eclipse, there are 2 means (not tested):
- use http://eslint.org/blog/2014/11/es6-jsx-support/ and as tern.java support ESLInt validation it should work.
- create a new tern linter plugin which uses https://github.com/STRML/JSXHint (but it seems that it's deprecated compare to ESLInt)

**Comment by fbastian** [comment]
Thanks for the tip, I didn't realize ESLint needed an additional configuration file to enable JSX and ES6 support. It works. Of note: 
- the blog post you linked to is outdated: ES6 support is now part of the master branch of ESLint
- the configuration needed is described here: http://eslint.org/docs/user-guide/configuring.html
- In Properties > Tern > Validation > ESLint > Use config files, it seems that you enforce the use of a `eslint.json` file. According to the documentation, I think it should rather be a `.eslintrc` file (but do you need to enforce a name anyway?)

Thanks for your help.

**Comment by fbastian** [comment]
You can actually use whatever name you want for the ESLint configuration file, by typing its name. Browsing will reset to blank value unless the name matches `eslint.json`
